project:
  type: website
  output-dir: _site
  resources:
    - "*.png"
    - "*.jpg"
    - "*.jpeg"
    - "*.svg"
    - "styles.css"

website:
  title: "ARS"
  favicon: logo.png
  navbar:
    background: "#f2f2f2"
    foreground: "#13252b"
    title: false
    left: []
    right: []
    search: true
  sidebar: false
format:
  html:
    theme: custom.scss
    css: styles.css
    toc: false
    embed-resources: true
    page-layout: custom