project:
  type: website
  output-dir: _site

website:
  title: "ARS"
  favicon: logo.png
  navbar:
    background: "#f2f2f2"
    foreground: "#13252b"
    title: false
    left: []
    right: []
    search: false
  sidebar: false
  search:
    location: navbar
    type: overlay

format:
  html:
    theme: custom.scss
    css: styles.css
    toc: false
    page-layout: custom