project:
  type: website
  output-dir: _site

website:
  title: ""
  favicon: logo.png
  navbar:
    background: "#fef9e7"
    foreground: "#34495e"
    title: false
    left: []
    right: []
    search: true
  sidebar: false
  search:
    location: navbar
    type: overlay

format:
  html:
    theme: custom.scss
    css: styles.css
    toc: false
    page-layout: custom